metadata:
  name: prometheus
spec:
  displayName: Prometheus
  provider: Prometheus
  description: |-
    Systems monitoring and alerting toolkit.
  kfdefApplications: ['prometheus-cluster', 'prometheus-operator']
  route: prometheus-portal
  img: images/prometheus.svg
  category: Managed service
  docsLink: https://prometheus.io/docs/
  quickStart: ''
  tutorial: https://airflow.apache.org/
  tutorialLength: 15
  howDoI: https://airflow.apache.org/
  howDoILength: 15
  getStartedLink: https://airflow.apache.org/
  getStartedMarkdown: "# Getting started"
