FROM registry.access.redhat.com/ubi9/go-toolset:1.26@sha256:5d26ff5606bd6590930e7cfc202b510e3fe2c7a7a1720860f444ab49c45128cb AS builder

USER root

ARG TARGETOS
ARG TARGETARCH
ARG OPERATOR_VERSION=unknown

WORKDIR /usr/src/app

COPY dashboard-operator/go.mod dashboard-operator/go.sum ./
RUN go mod download

COPY dashboard-operator/cmd/ cmd/
COPY dashboard-operator/api/ api/
COPY dashboard-operator/internal/ internal/

RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -a \
    -ldflags="-s -w -X 'github.com/opendatahub-io/odh-dashboard/dashboard-operator/internal/controller.Version=${OPERATOR_VERSION}'" \
    -tags strictfipsruntime -o /tmp/manager ./cmd/manager

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:dd334afa72444fa46238fcf9e6bd399245adf746378735348cf84b9dfdca38f1

WORKDIR /

COPY --from=builder /tmp/manager .
COPY --chown=65532:0 manifests/ /opt/manifests/dashboard/
RUN chmod -R g+w /opt/manifests/dashboard/modules/ \
    && chmod g+w /opt/manifests/dashboard/odh/params.env \
    && chmod g+w /opt/manifests/dashboard/odh/standalone/params.env \
    && chmod g+w /opt/manifests/dashboard/rhoai/params.env \
    && chmod g+w /opt/manifests/dashboard/rhoai/standalone/params.env \
    && chmod g+w /opt/manifests/dashboard/sidecar/params.env

USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-dashboard-operator-container" \
      name="managed-open-data-hub/odh-dashboard-operator-rhel9" \
      description="odh-dashboard-operator" \
      summary="odh-dashboard-operator" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-dashboard-operator" \
      io.k8s.description="odh-dashboard-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
