kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - services
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - route.openshift.io
  resources:
  - routes
