apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- custom-resource-definition.yaml
- role.yaml
- cluster-role.yaml
- service-account.yaml
- role-binding.yaml
- cluster-role-binding.yaml
- deployment.yaml
- routes.yaml
- service.yaml
- odh-application.yaml
- odh-document.yaml
