kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kfdef.apps.kubeflow.org
    resources:
      - kfdefs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    verbs:
      - create
      - delete
      - get
      - patch
      - update
      - watch
    resources:
      - configmaps
      - secrets
  - apiGroups:
      - batch
    verbs:
      - create
      - delete
      - get
      - patch
      - update
      - watch
    resources:
      - cronjobs
      - jobs
  - apiGroups:
      - image.openshift.io
    verbs:
      - create
      - get
      - patch
    resources:
      - imagestreams
